# baseURL = "http://example.org/"
baseURL = "https://balashov-artem.github.io/Portfolio/"
publoshDir = "docs"
languageCode = "en-us"
title = "Balashov 1111 Artem"
theme = "hugo-creative-portfolio-theme"

[params]
  style = "blue"
  description = "This is Balashov's Artem portfolio. For more information please contact me"
  copyright = "Made by Balashov Artem"
  sidebarAbout = [
    "Balashov Artem Portfolio",
    "Это мое будущее портфолио, тут скоро будет какой-нибудь внятный текст, но пока его тут нет"
  ]

  email = "Balashow.Artem@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/balashov301"
  googleplus    = "https://plus.google.com/u/0/101089597512299598557"
  email = "Balashow.Artem@gmail.com"
